### ISSUE TITLE
How to run composer install on production systems? No npm, yarn, ... available.

### ISSUE THREAD

**Issue by Defcon0** [fxpio/foxy#16]
Hello,

I recently installed my project to the live system. Now I want to do a `composer install`. Unfortunately now everytime the composer hook runs and looks for yarn or npm (which of course are both not installable on a live server). Is there any flag to deactivate foxy while running `composer install`?

Removing the foxy section from composer.json didn't help either :-(

Bye Defcon0

**Comment by schmunk42** [comment]
> Can be overridden by `FOXY__ENABLED="false"` environment variable.

https://github.com/fxpio/foxy/blob/71b8792664bf2fce286a6cdb0ac5201156f6e37c/Resources/doc/config.md#define-the-config-in-a-environment-variable

**Comment by Defcon0** [comment]
Thanks :-)
